version: '3.5'

services:
  db:
    image: postgres
    container_name: books_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - 5432:5432
